#!/bin/bash

## Simple single process job that uses 4 cores

#SBATCH -A "app=test"
#SBATCH -J Dada
#SBATCH -p high
#SBATCH -n 1
#SBATCH --cpus-per-task=24
#SBATCH -t 12:00:00
#SBATCH --output=SlurmOutput/dada-slurm-%j.out

# Running r version 4
module load R/4.0.2

# Cutadaptenv is my conda env with cutadapt in it
# others may need to activate their own conda enviornment

source activate cutadaptenv

pwd

Rscript RScripts/07_DadaInator.R

